name: Improve Markdown File

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  improve-md:
    runs-on: ubuntu-latest
    steps:
      # Checkout current repository with full history
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for git diff to work
          token: ${{ secrets.GITHUB_TOKEN }}

      # Setup Python for the OpenAI dependency
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Use your markdown improver action
      - name: Improve Markdown
        uses: Darshan-222004/darshan-md-improver@main
        with:
          repo: "${{ github.repository }}"
          mdfile: "README.md"
          purpose: "introduce a programming concept"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Optional: Show the changes made
      - name: Show diff
        run: git diff HEAD~1 -- README.md || echo "No changes made"
