name: Test Darshan Markdown Improver

on:
  push:
    branches: [main]  # or manually trigger with workflow_dispatch

jobs:
  improve-md:
    runs-on: ubuntu-latest

    steps:
      - name: Use Darshan's Markdown Improver Action
        uses: Darshan-222004/darshan-md-improver@v2
        with:
          repo: "https://github.com/Darshan-222004/test-md-usage.git"
          mdfile: "sample.md"
          purpose: "Introduce a programming concept"

