name: Improve Markdown File
on: workflow_dispatch

jobs:
  improve-md:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run Markdown Improver
        uses: Darshan-222004/darshan-md-improver@main
        with:
          repo: "${{ github.repository }}"
          mdfile: "README.md"
          purpose: "introduce a programming concept"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
