name: Improve Markdown

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  improve-markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Use the Markdown Improver Action
        uses: Darshan-222004/darshan-md-improver@v2
        with:
          repo: "https://github.com/Darshan-222004/test-md-usage.git"
          mdfile: "sample.md"
          purpose: "Introduce a programming concept"
