name: Improve Markdown File

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  improve-md:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Improve Markdown using local action
        uses: ./
        with:
          repo: "https://github.com/${{ github.repository }}"
          mdfile: "README.md"
          purpose: "introduce a programming concept"
          token: ${{ secrets.GH_TOKEN }}
