name: Improve Markdown File

on:
  workflow_dispatch:

jobs:
  improve-md:
    runs-on: ubuntu-latest

    steps:
      - name: Use Markdown Improver
        uses: Darshan-222004/darshan-md-improver@v2
        with:
          repo: https://github.com/Darshan-222004/your-target-repo
          mdfile: README.md
          purpose: introduce a programming concept
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
